import type { PrismaClient } from '../../generated/prisma';
import { EventType, EventStatus } from '../../generated/prisma';
import { prisma } from '../../lib/prisma';

const EVENT_DATA = [
  {
    title:                'Design Systems Summit 2026',
    description:          'A full-day conference exploring the future of design systems, component libraries, and cross-team collaboration at scale. Featuring speakers from Figma, Shopify, and Atlassian.',
    type:                 EventType.CONFERENCE,
    status:               EventStatus.UPCOMING,
    date:                 '2026-03-28',
    time:                 '9:00 AM EST',
    duration:             '8 hours',
    image:                'https://picsum.photos/800/400?random=1',
    isFree:               false,
    price:                '$149',
    attendees:            842,
    maxAttendees:         1200,
    tags:                 ['Design Systems', 'Components', 'Figma', 'Tokens'],
    url:                  'https://designsystemssummit.com',
    hostName:             'Nathan Curtis',
    hostRole:             'Design Systems Consultant',
    hostAvatar:           'https://picsum.photos/100/100?random=101',
    registrationDeadline: '2026-03-25',
  },
  {
    title:                'Figma Advanced Workshop',
    description:          "Deep dive into Figma's advanced features — Auto Layout, Variables, Component Properties, and Dev Mode. Hands-on exercises throughout.",
    type:                 EventType.WORKSHOP,
    status:               EventStatus.UPCOMING,
    date:                 '2026-04-02',
    time:                 '1:00 PM EST',
    duration:             '3 hours',
    image:                'https://picsum.photos/800/400?random=2',
    isFree:               false,
    price:                '$49',
    attendees:            156,
    maxAttendees:         200,
    tags:                 ['Figma', 'Auto Layout', 'Variables', 'Workshop'],
    url:                  'https://figma.com/events',
    hostName:             'Figma Team',
    hostRole:             'Official Figma Workshop',
    hostAvatar:           'https://picsum.photos/100/100?random=102',
    registrationDeadline: '2026-03-31',
  },
  {
    title:       'UX Research Methods Live',
    description: 'Live session covering modern UX research methods — from guerrilla testing to unmoderated studies. Q&A with the audience throughout.',
    type:        EventType.WEBINAR,
    status:      EventStatus.ARCHIVED,
    date:        '2026-03-23',
    time:        '2:00 PM EST',
    duration:    '1.5 hours',
    image:       'https://picsum.photos/800/400?random=3',
    isFree:      true,
    price:       null,
    attendees:   1247,
    maxAttendees:null,
    tags:        ['UX Research', 'User Testing', 'Live'],
    url:         'https://nngroup.com/events',
    hostName:    'Nielsen Norman Group',
    hostRole:    'UX Research Leaders',
    hostAvatar:  'https://picsum.photos/100/100?random=103',
  },
  {
    title:                'AI x Design Hackathon',
    description:          'A 48-hour hackathon where designers and developers collaborate to build AI-powered design tools. $10,000 in prizes across three categories.',
    type:                 EventType.HACKATHON,
    status:               EventStatus.UPCOMING,
    date:                 '2026-04-15',
    time:                 '10:00 AM EST',
    duration:             '48 hours',
    image:                'https://picsum.photos/800/400?random=4',
    isFree:               true,
    price:                null,
    attendees:            389,
    maxAttendees:         500,
    tags:                 ['AI', 'Hackathon', 'Design Tools', 'Prize'],
    url:                  'https://hackathon.design',
    hostName:             'Design x AI Community',
    hostRole:             'Community Organizers',
    hostAvatar:           'https://picsum.photos/100/100?random=104',
    registrationDeadline: '2026-04-13',
  },
  {
    title:                'Awwwards Submission Deadline',
    description:          'Last day to submit your website or project for consideration in the Awwwards Site of the Year 2026. Winners announced in May.',
    type:                 EventType.AWARD,
    status:               EventStatus.UPCOMING,
    date:                 '2026-04-30',
    time:                 '11:59 PM CET',
    duration:             'Deadline',
    image:                'https://picsum.photos/800/400?random=5',
    isFree:               false,
    price:                '$85',
    attendees:            2103,
    maxAttendees:         null,
    tags:                 ['Award', 'Web Design', 'Submission', 'Awwwards'],
    url:                  'https://awwwards.com',
    hostName:             'Awwwards',
    hostRole:             'Web Design Awards',
    hostAvatar:           'https://picsum.photos/100/100?random=105',
    registrationDeadline: '2026-04-30', // submission IS the deadline
  },
  {
    title:       'Design Tokens Deep Dive',
    description: 'A recorded session on implementing design tokens across web, iOS, and Android. Covers naming conventions, tooling, and real-world case studies.',
    type:        EventType.WEBINAR,
    status:      EventStatus.ARCHIVED,
    date:        '2026-03-10',
    time:        '3:00 PM EST',
    duration:    '1 hour',
    image:       'https://picsum.photos/800/400?random=6',
    isFree:      true,
    price:       null,
    attendees:   934,
    maxAttendees:null,
    tags:        ['Design Tokens', 'Tokens Studio', 'Multi-platform'],
    url:         'https://youtube.com',
    hostName:    'Tokens Studio',
    hostRole:    'Design Tokens Specialists',
    hostAvatar:  'https://picsum.photos/100/100?random=106',
  },
  {
    title:                'Interaction Design Foundation Meetup',
    description:          "Monthly local meetup for IxDF members and design enthusiasts. This month's topic: designing for accessibility in 2026.",
    type:                 EventType.MEETUP,
    status:               EventStatus.UPCOMING,
    date:                 '2026-04-08',
    time:                 '6:30 PM EST',
    duration:             '2 hours',
    image:                'https://picsum.photos/800/400?random=7',
    isFree:               true,
    price:                null,
    attendees:            87,
    maxAttendees:         120,
    tags:                 ['Meetup', 'Accessibility', 'IxDF', 'Community'],
    url:                  'https://interaction-design.org',
    hostName:             'IxDF Community',
    hostRole:             'Design Community',
    hostAvatar:           'https://picsum.photos/100/100?random=107',
    registrationDeadline: null, // free drop-in meetup
  },
  {
    title:                'Motion Design Masterclass',
    description:          'Three-day intensive workshop on motion design for interfaces — from micro-interactions to full page transitions using Rive and Framer.',
    type:                 EventType.WORKSHOP,
    status:               EventStatus.UPCOMING,
    date:                 '2026-05-05',
    time:                 '10:00 AM EST',
    duration:             '3 days',
    image:                'https://picsum.photos/800/400?random=8',
    isFree:               false,
    price:                '$299',
    attendees:            64,
    maxAttendees:         80,
    tags:                 ['Motion Design', 'Rive', 'Framer', 'Animation'],
    url:                  'https://motiondesign.school',
    hostName:             'Motion Design School',
    hostRole:             'Motion Design Educators',
    hostAvatar:           'https://picsum.photos/100/100?random=108',
    registrationDeadline: '2026-05-01',
  },
  {
    title:                'CSS Day 2026',
    description:          'The premier conference for CSS and design engineering. Two days of deep technical talks on modern CSS, design tokens, and styling architecture.',
    type:                 EventType.CONFERENCE,
    status:               EventStatus.UPCOMING,
    date:                 '2026-05-14',
    time:                 '9:00 AM CET',
    duration:             '2 days',
    image:                'https://picsum.photos/800/400?random=9',
    isFree:               false,
    price:                '$399',
    attendees:            521,
    maxAttendees:         600,
    tags:                 ['CSS', 'Design Engineering', 'Web', 'Conference'],
    url:                  'https://cssday.nl',
    hostName:             'CSS Day',
    hostRole:             'Annual CSS Conference',
    hostAvatar:           'https://picsum.photos/100/100?random=109',
    registrationDeadline: '2026-05-10',
  },
  {
    title:                'Figma Config 2026',
    description:          "Figma's annual design conference featuring product announcements, hands-on workshops, and community talks from designers around the world.",
    type:                 EventType.CONFERENCE,
    status:               EventStatus.UPCOMING,
    date:                 '2026-06-03',
    time:                 '9:00 AM PST',
    duration:             '2 days',
    image:                'https://picsum.photos/800/400?random=10',
    isFree:               false,
    price:                '$199',
    attendees:            3847,
    maxAttendees:         5000,
    tags:                 ['Figma', 'Config', 'Conference', 'Product Design'],
    url:                  'https://config.figma.com',
    hostName:             'Figma',
    hostRole:             'Design Platform',
    hostAvatar:           'https://picsum.photos/100/100?random=110',
    registrationDeadline: '2026-05-28',
  },
  {
    title:                'UX Writing Summit',
    description:          'Virtual summit dedicated to UX writing, content design, and plain language. Hear from writers at Google, Duolingo, and Mailchimp.',
    type:                 EventType.WEBINAR,
    status:               EventStatus.UPCOMING,
    date:                 '2026-05-22',
    time:                 '10:00 AM EST',
    duration:             '6 hours',
    image:                'https://picsum.photos/800/400?random=11',
    isFree:               false,
    price:                '$79',
    attendees:            418,
    maxAttendees:         800,
    tags:                 ['UX Writing', 'Content Design', 'Copy', 'Summit'],
    url:                  'https://uxwritingsummit.com',
    hostName:             'UX Writing Hub',
    hostRole:             'UX Writing Community',
    hostAvatar:           'https://picsum.photos/100/100?random=111',
    registrationDeadline: '2026-05-19',
  },
  {
    title:                'Dribbble Design Awards 2026',
    description:          'Annual awards celebrating the best design work submitted to Dribbble. Categories include UI, Brand, Illustration, and Motion.',
    type:                 EventType.AWARD,
    status:               EventStatus.UPCOMING,
    date:                 '2026-06-20',
    time:                 '12:00 PM EST',
    duration:             'Ceremony',
    image:                'https://picsum.photos/800/400?random=12',
    isFree:               true,
    price:                null,
    attendees:            9241,
    maxAttendees:         null,
    tags:                 ['Award', 'Dribbble', 'Design', 'Community'],
    url:                  'https://dribbble.com/awards',
    hostName:             'Dribbble',
    hostRole:             'Design Community Platform',
    hostAvatar:           'https://picsum.photos/100/100?random=112',
    registrationDeadline: null, // free ceremony, no deadline
  },
];

/** Recomputes UPCOMING vs ARCHIVED from the event date. LIVE is never auto-assigned. */
function computeStatus(date: string, hardcoded: EventStatus): EventStatus {
  if (hardcoded === EventStatus.LIVE) return EventStatus.LIVE; // keep manual LIVE as-is
  return new Date(date + 'T23:59:59') < new Date() ? EventStatus.ARCHIVED : EventStatus.UPCOMING;
}

/**
 * Upserts all static event records.
 * Status is recomputed from the event date on every run so past events
 * automatically flip to ARCHIVED instead of staying frozen.
 */
export async function seedEvents(prisma: PrismaClient): Promise<void> {
  let count = 0;
  for (const event of EVENT_DATA) {
    const status = computeStatus(event.date, event.status);
    await prisma.event.upsert({
      where:  { title: event.title },
      create: { ...event, status },
      update: {
        description:          event.description,
        status,
        attendees:            event.attendees,
        registrationDeadline: event.registrationDeadline,
      },
    });
    count++;
  }
  console.log(`✓ Events — upserted ${count}`);
}

// ── Standalone runner ─────────────────────────────────────────────────────────
if (require.main === module) {
  seedEvents(prisma)
    .catch((err) => { console.error(err); process.exit(1); })
    .finally(() => prisma.$disconnect());
}
